Repository mvallim/live-custom-ubuntu-from-scratch, pull requests merged in 2021-04, with the labels that each got.

#20 Fix error on install Ubuntu
  README.md
  scripts/chroot_build.sh
Labels: bug

#22 Update readme
  README.md
Labels: documentation

#24 Allow customization without fork
  README.md
  scripts/build.sh
  scripts/configuration.sh
Labels: enhancement
